apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: hello-service-backend
  labels:
    app: hello-service-backend
spec:
  selector:
    matchLabels:
      app: hello-service-backend
  replicas: 1 # indica al controlador que ejecute 2 pods
  template:
    metadata:
      labels:
        app: hello-service-backend
    spec:
      containers:
      - name: hello-service-backend
        image: dkeyceo/hello-k8s-service:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service-backend
  labels:
    app: hello-service-backend
spec:
  selector:
    app: hello-service-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer