apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-keycloak-k8s
  labels:
    app: backend-keycloak-k8s
spec:
  selector:
    matchLabels:
      app: backend-keycloak-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-keycloak-k8s
    spec:
      containers:
      - name: backend-keycloak-k8s
        image: dkeyceo/backend-keycloak-k8s:v3
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: backend-keycloak-k8s
  labels:
    app: backend-keycloak-k8s
spec:
  selector:
    app: backend-keycloak-k8s
  ports:
    - nodePort: 30007
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
