apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-keycloak-k8s
  labels:
    app: backend-keycloak-k8s
spec:
  selector:
    matchLabels:
      app: backend-keycloak-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-keycloak-k8s
    spec:
      containers:
      - name: backend-keycloak-k8s
        image: dkeyceo/backend-keycloak-k8s:v1
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: backend-keycloak-k8s
  labels:
    app: backend-keycloak-k8s
spec:
  selector:
    app: backend-keycloak-k8s
  ports:
    - nodePort: 30007
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
